### ISSUE TITLE
[Feature Request]: Alternative samplers

### ISSUE THREAD

**Issue by patrickjonesdotca** [deforum-art/sd-webui-text2video#106]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Would allow for the full range of samplers on the t2v model

### Proposed workflow

1. Go to ModelScope tab on AUTOMATIC1111
2. Select model (Say EulerA or PLMS)
3. Press Generate
4. Enjoy

**Comment by hithereai** [comment]
You already opened the exact same thing a few days ago: https://github.com/deforum-art/sd-webui-text2video/issues/100

**Comment by patrickjonesdotca** [comment]
Sorry...couldn't find the original.
