### ISSUE TITLE
[Feature Request]: Finding out what seed was used

### ISSUE THREAD

**Issue by justinwking** [deforum-art/sd-webui-text2video#107]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

I appreciate you guys taking the time to make this extension, and find it valuable. In the process of working with it, I noticed some small details that might be improved upon. 

Is there a way to find out what seed was used to generate a video. For example, possibly creating a text file listing the settings used to generate the image, like the way that it is possible to do so in Deforum? 

Also is there a way to prefix the video file with the name of the folder, so that if someone wanted to aggregate all the generated videos, they can find the associated folder, and I don't have to rename every video? 

I apologize that I don't have enough experience to contribute any code, but appreciate the consideration.

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

**Comment by kabachuha** [comment]
It's a part of https://github.com/deforum-art/sd-webui-text2video/pull/56, but that PR got stuck

**Comment by rookiemann** [comment]
I'd like to add something please. I too wanted to see what the random generated seed was so I put a simple print statement

`                print(seed, "  <--- seed") `

on line 237 of t2v_pipeline.py to see it on the console and it was always 1. If I manually changed the seed on the gui it would always select the last digit of the string such as 42 would just be 2 or 55 would just be 5 etc.

I haven't looked further than that I'm just seeing this now.

**Comment by kabachuha** [comment]
Now it prints the generation params before making an animation

**Comment by pmonck** [comment]
When using -1 as the seed (I assume this is to generate a random seed), the seed value is printed as -1 in the params. Would it be possible to make it print the actual random seed used for the generation instead?

**Comment by mockinbirdy** [comment]
> Now it prints the generation params before making an animation

Can it be automatically saved in the file name?
