### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by mhussar** [deforum-art/sd-webui-text2video#119]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Are you using the latest version of the extension?

- [X] I have the modelscope text2video extension updated to the lastest version and I still have the issue.

### What happened?

getting this error just for modelscope:
Exception occurred: GaussianDiffusion.ddim_sample_loop() got an unexpected keyword argument 'mask'

### Steps to reproduce the problem

1. Go to .... text2Video and enter in simple prompt cat running
2. Press ....generate
3. ... get Exception occurred: GaussianDiffusion.ddim_sample_loop() got an unexpected keyword argument 'mask' in the command window

### What should have happened?

before the recent update modelscope was working fine creating a video

### WebUI and Deforum extension Commit IDs

webui commit id - 
txt2vid commit id -

### What GPU were you using for launching?

rtx 3090 24 vram

### On which platform are you launching the webui backend with the extension?

Local PC setup (Windows)

### Settings

default settings  nothing fancy

### Console logs

```Shell
not sure where
```

**Comment by kabachuha** [comment]
If you're on Windows, install Windows Terminal and launch your `webui-user.bat` inside it. Once the bug occurs, right-click the tab and click save or copy logs

It's hard to get the cause of the error without the traceback

**Comment by mhussar** [comment]
text2video — The model selected is:  ModelScope
 text2video extension for auto1111 webui
Git commit: cac54c26 (Thu Apr  6 16:46:13 2023)
Starting text2video
Pipeline setup
config namespace(framework='pytorch', task='text-to-video-synthesis', model={'type': 'latent-text-to-video-synthesis', 'model_args': {'ckpt_clip': 'open_clip_pytorch_model.bin', 'ckpt_unet': 'text2video_pytorch_model.pth', 'ckpt_autoencoder': 'VQGAN_autoencoder.pth', 'max_frames': 16, 'tiny_gpu': 1}, 'model_cfg': {'unet_in_dim': 4, 'unet_dim': 320, 'unet_y_dim': 768, 'unet_context_dim': 1024, 'unet_out_dim': 4, 'unet_dim_mult': [1, 2, 4, 4], 'unet_num_heads': 8, 'unet_head_dim': 64, 'unet_res_blocks': 2, 'unet_attn_scales': [1, 0.5, 0.25], 'unet_dropout': 0.1, 'temporal_attention': 'True', 'num_timesteps': 1000, 'mean_type': 'eps', 'var_type': 'fixed_small', 'loss_type': 'mse'}}, pipeline={'type': 'latent-text-to-video-synthesis'})
device cuda
Working in txt2vid mode
  0%|                                                                            | 0/1 [00:00<?, ?it/s]latents torch.Size([1, 4, 24, 32, 32]) tensor(-0.0051, device='cuda:0') tensor(0.9974, device='cuda:0')
Traceback (most recent call last):
  File "D:\Projects\Personal\AI_ImageCreation\StableDiffusion1111_010723\stable-diffusion-webui\extensions\sd-webui-modelscope-text2video\scripts\text2vid.py", line 92, in process
    process_modelscope(skip_video_creation, ffmpeg_location, ffmpeg_crf, ffmpeg_preset, fps, add_soundtrack, soundtrack_path, \
  File "D:\Projects\Personal\AI_ImageCreation\StableDiffusion1111_010723\stable-diffusion-webui\extensions\sd-webui-modelscope-text2video\scripts\text2vid.py", line 234, in process_modelscope
    samples, _ = pipe.infer(prompt, n_prompt, steps, frames, seed + batch if seed != -1 else -1, cfg_scale,
  File "D:\Projects\Personal\AI_ImageCreation\StableDiffusion1111_010723\stable-diffusion-webui/extensions/sd-webui-text2video/scripts\modelscope\t2v_pipeline.py", line 245, in infer
    x0 = self.diffusion.ddim_sample_loop(  File "D:\Projects\Personal\AI_ImageCreation\StableDiffusion1111_010723\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
TypeError: GaussianDiffusion.ddim_sample_loop() got an unexpected keyword argument 'mask'
Exception occurred: GaussianDiffusion.ddim_sample_loop() got an unexpected keyword argument 'mask'
