### ISSUE TITLE
Exception occured 'NoneType' object has no attribute 'cond_stage_model'

### ISSUE THREAD

**Issue by toyxyz** [deforum-art/sd-webui-text2video#13]
If I start the webui and then generate the video, it works fine. However, when I click the generate button for the second time, an error occurs.

```
Exception occured
'NoneType' object has no attribute 'cond_stage_model'
```

**Comment by sALTaccount** [comment]
Getting the same error on the latest commit (eed8524d). Will look into it further to determine a cause

**Comment by kabachuha** [comment]
@sALTaccount could you collect a log and make a new issue about it, with all the needed data?
