### ISSUE TITLE
[Feature Request]: The same seed generate the same video every time with vid2vid

### ISSUE THREAD

**Issue by alexfredo** [deforum-art/sd-webui-text2video#143]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Hi, is it normal that the same seed creates a different video every time with vid2vid even if I don't change the settings? how fix that Thanks.

### Proposed workflow

add seed 1 for generate the same video

**Comment by hithereai** [comment]
@kabachuha xformers?

**Comment by kabachuha** [comment]
@alexfredo open bug report as bug report, not a feature request
