### ISSUE TITLE
[Feature Request]: Add option to store the model in RAM/VRAM between runs

### ISSUE THREAD

**Issue by kabachuha** [deforum-art/sd-webui-text2video#23]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

- [x] 1. Keep in VRAM
- [ ] 2. Keep in RAM

Model IO takes a bulk of runtime, so if the user has a plenty of VRAM, it would be nice to store the core model in it

### Proposed workflow

1. Select store model in RAM in extension settings
3. Do runs without waiting for model loading/unloading from disc

**Comment by hithereai** [comment]
VRAM keeping is in place already, can keep it open for RAM keeping as well.
