### ISSUE TITLE
[Feature Request]: img2vid

### ISSUE THREAD

**Issue by gsgoldma** [deforum-art/sd-webui-text2video#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

take an existing image, and make a video that starts with it or incorporates it in some frame

### Proposed workflow

1. Go to .... 
2. Press ....
3. ...

### Additional information

We already have a lot of methods for vid2vid, including using img2img on each image in the video, or pix2pix, or even scripts that do it. We don't have an img2vid yet though.
Not sure if this is already in the works.

**Comment by kabachuha** [comment]
Masking the first frame + denoising rest of the latents sounds like a good solution for this one 👍

**Comment by Compviztr** [comment]
Can this technique from @alexvw be merged in https://github.com/alexvw/img2video

**Comment by kabachuha** [comment]
Sounds like a good idea

**Comment by kabachuha** [comment]
Implemented
