### ISSUE TITLE
[Feature Request]: Add attention and VAE slicing

### ISSUE THREAD

**Issue by nagolinc** [deforum-art/sd-webui-text2video#50]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

"Long Video Generation

You can optimize for memory usage by enabling attention and VAE slicing and using Torch 2.0. This should allow you to generate videos up to 25 seconds on less than 16GB of GPU VRAM."

https://twitter.com/Norod78/status/1638841615384031233

### Proposed workflow

1. Go to vid2vid tab
2. Frames = 1024
3. run

---

TODO:

- [ ] Add attention slicing https://github.com/huggingface/diffusers/blob/b94880e536d5e46acc374a5cebe49b442466d913/src/diffusers/models/controlnet.py#L372, but may be already in the core Auto as well, need to check out
- [x] Add VAE slicing https://github.com/huggingface/diffusers/blob/b94880e536d5e46acc374a5cebe49b442466d913/src/diffusers/models/autoencoder_kl.py#L186, need to check if it's already in Auto as well

**Comment by kabachuha** [comment]
Nope, Auto is not built on Diffusers from start and it's wrong to bring this large additional dependency

**Comment by kabachuha** [comment]
Else the Auto itself would be built on Diffusers. The main reason for this is everything should be hackable

**Comment by sALTaccount** [comment]
VAE decodes framewise anyways, you can decode without any spiking using something like
```
video_data = torch.cat([self.vae.decode(x.unsqueeze(0)) for x in video_data])
```
The reason its so high right now is because they batch all frame decodes

**Comment by kabachuha** [comment]
```python
for chunk in chunks:
      chunk = 1. / scale_factor * chunk

      chunk = rearrange(chunk, 'b c f h w -> (b f) c h w')
      output_chunk = self.autoencoder.decode(chunk)
      cpu_chunk = output_chunk.cpu()
      del output_chunk
      output_chunks.append(cpu_chunk)
      x += 1
```

As I see it already decodes them one by one, so no worries here

**Comment by sALTaccount** [comment]
Ah my bad, I don't think that was in the codebase last time I checked

**Comment by kabachuha** [comment]
Do you have any idea on how to lighten the previous stage, the actual text2video? I have 4gbs, but it OOMs when the model is loading for some reason

**Comment by sALTaccount** [comment]
I'll need to look into it and see if it even matters / you fixed it, but the model is actually using just a standard VAE and text encoder, but the mode files are like 3-5 gb. However, just taking a peek inside the VQGAN_autoencoder.pth, we can see https://pastebin.com/fy80H8zA that there is a LOT more than just the VAE lol. It appears to be the entire stable diffusion checkpoint. Haven't checked the text encoder yet. So if all of these are being loaded and then discarded, it could maybe cause some OOM on model loading

**Comment by ExponentialML** [comment]
@sALTaccount Nice catch. 

You should be able to use the VAEs from here. https://huggingface.co/damo-vilab/text-to-video-ms-1.7b/tree/main/vae

**Comment by kabachuha** [comment]
Btw, I'm switching to the standard text encoder right now on my wip branch to allow for prompt weights and stuff

**Comment by kabachuha** [comment]
Uh, no, seems like they use different lengths
