### ISSUE TITLE
[Bug]: i run it  on rtx3060ti           8g,it  produce results   but  with            black picture   and videos                        

### ISSUE THREAD

**Issue by jackylee1** [deforum-art/sd-webui-text2video#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Are you using the latest version of the extension?

- [X] I have the modelscope text2video extension updated to the lastest version and I still have the issue.

### What happened?

[Bug]: i run it  on rtx3060ti           8g,it  produce results   but  with            black picture   and videos                        

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

a  panda  eatting?

### WebUI and Deforum extension Commit IDs

webui commit id - latest
txt2vid commit id -latest

### What GPU were you using for launching?

rtx3060ti          8g

### On which platform are you launching the webui backend with the extension?

Local PC setup (Windows)

### Settings

nothing

### Console logs

```Shell
don't know
```

**Comment by deroc1** [comment]
Hello did you fixed the issue somehow? i have the same one.
